import Head from "next/head";
import { Inter } from "next/font/google";
import { withAuth } from "@/hoc/withAuth";
import { useAuthContext } from "@/state/auth";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  const { dispatch } = useAuthContext();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};
export default withAuth(Home);
